# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_item_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
