# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20170201_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
