# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_slot_slotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='times',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
